### ISSUE TITLE
RtfTemplate - configure variable bounds

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [ullenboom/jrtf#16]
When working with RtfTemplates I would like to change the variable prefix and suffix. For example to use `[ADDRESSLINE1]` instead of the default `%%ADDRESSLINE1%%`.

```
Rtf.template( new FileInputStream("template.rtf) )
   .setVariableBounds("[", "]")
   .inject( "ADDRESSLINE1", "tutego" )
   // ...
```

Use case:
I'm currently looking at jrtf to replace some old RTF-templating code that doesn't handle Unicode characters. But we already have a lot of templates using brackets `[, ]` as variable bounds instead of `%%`.

If you are interested in this feature, I could create a pull request.

**Comment by ullenboom** [comment]
sure, you can implement.
