### ISSUE TITLE
Full width table row

### ISSUE THREAD

**Issue by steliosph** [ullenboom/jrtf#2]
Hi, just found you app and i have to say that is good work.
Everything seems to be working correctly.

My issue is with the tables ( row ).
Creating the row like this
RtfPara.row("A", "  ", "B", "  ")
                .bottomCellBorder().topCellBorder().rightCellBorder()
                .leftCellBorder())

i can see in the RtfRow that autofit is disabled and that on RtfParam
when exporting were always doing this
out.append( "{\trowd\trautofit1\intbl\n"

Although this does work on libre office and the table is full width it will not work on microsoft word.

Any idea that we can do in order to get the table to be full width. ?

**Comment by GAlexMES** [comment]
@steliosph @ullenboom 
A bit late, but I need this feature too. I have a clue how to do it, and will try to implement it during the next week.

**Comment by tel** [comment]
```
@tel ...
```

:glares:

**Comment by tel** [comment]
jk, but ignoring now

**Comment by GAlexMES** [comment]
@steliosph 
A bit late, but anyway. You can call .setWidth() on your RtfTextPara to set's its width. You can use this to make your whole table wider. Just add it to every cell of your header row.
