### ISSUE TITLE
Examples in README does not compile

### ISSUE THREAD

**Issue by fatso83** [ullenboom/jrtf#23]
In the [A bit of Style](https://github.com/ullenboom/jrtf#a-bit-of-style) section you have this little snippet:
```java
rtf()
  .header(
    color( 0xff, 0, 0 ).at( 0 ),
    color( 0, 0xff, 0 ).at( 1 ),
    color( 0, 0, 0xff ).at( 2 ),
    font( "Calibri" ).at( 0 ) )
  .section(
	p( font( 1, "Second paragraph" ) ),
	p( color( 1, "green" ) )
  )
).out( out );
```

That doesn't actually compile, as there is no static method in `RtfHeader` matching the `(int, String)` signature. There is just [a single implementation](https://github.com/ullenboom/jrtf/blob/master/src/main/java/com/tutego/jrtf/RtfHeader.java#L55) of `font`, accepting a `String.

**Comment by fatso83** [comment]
Fixing that, the example would also fail at runtime, since an index of 0 is not valid:
```java
Exception in thread "main" com.tutego.jrtf.RtfException: Color index 0 ist out of range, has to be between 1 and 255
	at nimble.server.external.jrtf.RtfHeaderColor.at(RtfHeaderColor.java:76)
```

**Comment by ullenboom** [comment]
corrected
