### ISSUE TITLE
RtfPara.ul not rendering correct without ending par

### ISSUE THREAD

**Issue by frankball** [ullenboom/jrtf#24]
When generating Lists with bullets the list in RTF is not rendering the bullets and line breaks between multiple list entries:

    Rtf.rtf().section(
            RtfPara.ul("List entry 1"), 
            RtfPara.ul("List entry 2"), 
            RtfPara.ul("List entry 3"))
            .out(new OutputStreamWriter(fout));

Result with current master code:
![image](https://user-images.githubusercontent.com/21197462/62696285-6334f400-b9d8-11e9-8532-1096fda35647.png)

After appending ending par in RtfPara.ul:

    return new RtfPara() {
      @Override void rtf( Appendable out, boolean withEndingPar ) throws IOException {
        out.append( s );
        text.rtf( out );
        out.append( "\\par}" );
      }
    };
  
the result looks fine:
![image](https://user-images.githubusercontent.com/21197462/62696665-2e756c80-b9d9-11e9-864e-4c92872d7e12.png)

**Comment by ullenboom** [comment]
fixed
