### ISSUE TITLE
Picture not being added in template 

### ISSUE THREAD

**Issue by aronvvijv** [ullenboom/jrtf#29]
Is it able to add a picture in a template? Because the following is not working: 
`InputStream image = new FileInputStream("src/files/logo.jpg");
        Rtf.template(is).inject("COMPANY_LOGO", picture(image).size(64, 64, RtfUnit.POINT).type(RtfPicture.PictureType.JPG)
                .out(out);
`

**Comment by ullenboom** [comment]
It's unfortunately not possible and not that easy.
