### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by Catchwa** [ullenboom/jrtf#3]
Hi,

It'd be great if jRTF could be published to Maven. It'd make code that uses it a lot easier to maintain.

Thanks!

**Comment by vmartis** [comment]
+1

**Comment by mavarazy** [comment]
+1

**Comment by tchemit** [comment]
:+1: 
Hi @ullenboom , I just add a PR with a maven project file to make possible deployement to ossrh [1]. I also ask a project repository creation at this place [2].
Hope you will merge soon this PR.

Thanks.

[1] http://central.sonatype.org/pages/ossrh-guide.html
[2] https://issues.sonatype.org/browse/OSSRH-16177

**Comment by tchemit** [comment]
Hi @ullenboom , could you comment the jira issue to let me (or you of course) deploy the artifact to Maven Central [1].

If you are not the owner of the com.tutego groupId in OSSRH, do you know you is his owner ?

thanks.

[1] https://issues.sonatype.org/browse/OSSRH-16177

**Comment by ullenboom** [comment]
feel free to publish. thanks for the effort.

**Comment by tchemit** [comment]
Ok, do you have the time to add a comment to the OSSRH issue ? it would help us to make this possible ? thanks.

**Comment by tchemit** [comment]
Ok I just promoted a first release 0.7 based on his tag.
Let me know when you'd like to do anoter version, I will release it also to Maven Central.

**Comment by tchemit** [comment]
Ok @ullenboom , I think we can close this issue : http://repo1.maven.org/maven2/com/tutego/jrtf/0.7

**Comment by ullenboom** [comment]
Great!

Grüße

 Christian

--

/**
 * @author   Christian Ullenboom
<http://www.xing.com/profile/Christian_Ullenboom>
 * @email    ullenboom@gmail.com
 * @address  Schloßstr. 5, 47665 Sonsbeck, Germany
 * @tel      +49 (178) 56 42 74 0
 */

Die RetroBude (http://retrobu.de/) ist auf der Suche nach HEIMCOMPUTERN und
SPIELKONSOLEN. Gerne nehmen wir historische Heimcomputer, Software,
Literatur, Werbung und weitere Artefakte aus der Vergangenheit entgegen
(als Spende oder gegen Bezahlung). Bei uns sind die Sammlerstücke in guten
Händen.

tutego <http://www.tutego.de/>® unterstützt SOS Kinderdörfer
<http://www.sos-kinderdoerfer.de/>, die Deutsche Welthungerhilfe
<http://www.welthungerhilfe.de/> und Ärzte ohne Grenzen
<http://www.aerzte-ohne-grenzen.de/>. Helfen Sie mit!

2015-06-24 20:52 GMT+02:00 Tony CHEMIT <notifications@github.com>:

**Comment by AdamPalka** [comment]
@tchemit can you publish 0.8-SNAPSHOT version to Maven repository? After @ullenboom accept or reject my pull request.

@ullenboom is it ok with you?

**Comment by tchemit** [comment]
I will see where to deply it (a snapshot repository). Wake me up when everything is ready to deploy a snapshot.

**Comment by ullenboom** [comment]
its fine for sure.

**Comment by AdamPalka** [comment]
ok, so now I'm just wainting for my last pull request to be merged, at least I hope it will

**Comment by AdamPalka** [comment]
@tchemit we are ready to go with the SNAPSHOT version, deploy it :)

**Comment by tchemit** [comment]
Hi @AdamPalka , I will try this tomorrow.

**Comment by tchemit** [comment]
@AdamPalka , the snapshot is ready to be used.

Deployed here: https://oss.sonatype.org/content/repositories/snapshots/com/tutego/jrtf/0.8-SNAPSHOT/
